In [3]:
####Select Sales Data
import sqlite3
import pandas as pd
conn = sqlite3.connect("My_Data.db")
cursor = conn.cursor()

In [5]:
pd.read_csv('sales.csv').to_sql('sales',conn,if_exists = 'replace',index = False)

20

In [7]:
pd.read_sql_query('''
select sale_date , product, price From sales 
''',conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

In [8]:
###Where
pd.read_csv('hr_employees.csv').to_sql('employees',conn,if_exists = 'replace',index = False)

30

In [13]:
pd.read_sql_query('''
select name, department, salary, years_experience, city
from employees
where city = 'Chicago' AND years_experience > 10
''',conn)

   name  department  salary  years_experience     city
0  Lily  Operations   56000                17  Chicago

In [ ]:
#### Order by

In [20]:

pd.read_csv('realestate_listings.csv').to_sql('listings',conn,if_exists = 'replace',index = False)

25

In [21]:
pd.read_sql_query('''
select listing_id, neighborhood, bedrooms, sqft, list_price
from listings
order by sqft desc limit 3
''', conn)

   listing_id neighborhood  bedrooms  sqft  list_price
0         204    Riverside         5  3736      979000
1         206  Maple Grove         5  3693     1001000
2         209  Maple Grove         1  3499      661000

In [22]:
###Grouping
pd.read_csv('marketing_campaigns.csv').to_sql('campaigns',conn,if_exists = 'replace',index = False)

40

In [26]:
pd.read_sql_query('''
select  sum(impressions) As Total_Impressions 
from campaigns
group by week
''',conn)

   Total_Impressions
0             181454
1              74972
2             193242
3             180795
4             264615
5             229892
6             235470
7             253354

In [28]:
###Having
pd.read_csv('restaurant_orders.csv').to_sql('orders',conn,if_exists = 'replace',index = False)

50

In [34]:
pd.read_sql_query('''
select order_date, sum(order_total) as Date_total
From orders 
group by order_date
Having sum(order_total) > 400
''',conn)

   order_date  Date_total
0  2026-10-02      492.14
1  2026-10-05      850.10
2  2026-10-07      415.94
3  2026-10-12      633.98

In [35]:
###aggregate
pd.read_csv('clinic_visits.csv').to_sql('visits',conn,if_exists = 'replace',index = False)

35

In [43]:
pd.read_sql_query('''
select doctor, count(*) as total_visits, 
        round(AVG(patient_age),0) as Average_Age,
        Max(wait_minutes) AS Highest_wait
    from visits
    group by doctor
    ''',conn)

      doctor  total_visits  Average_Age  Highest_wait
0  Dr. Adams             9         47.0            75
1   Dr. Chen             5         58.0            50
2  Dr. Gomez             6         34.0            75
3  Dr. Patel             8         45.0            59
4  Dr. Scott             7         45.0            63

In [46]:
###Join
pd.read_csv('bank_customers.csv').to_sql('customers',conn,if_exists = 'replace',index = False)
pd.read_csv('bank_transactions.csv').to_sql('transactions',conn,if_exists = 'replace',index = False)

45

In [51]:
pd.read_sql_query('''
select branch, t.transaction_type, sum(t.amount) as Total_Amount
from transactions as t
join customers as c on t.customer_id = c.customer_id
group by branch 
''',conn)

      branch transaction_type  Total_Amount
0    Airport          Payment      15177.98
1    Main St          Payment       3581.19
2  Northgate       Withdrawal      19546.49
3   Westside         Transfer      13996.30